FROM centos/systemd
RUN yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo; yum -y install yum-utils device-mapper-persistent-data lvm2 docker-ce docker-ce-cli containerd.io; yum clean all; curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose; chgrp docker /usr/local/bin/docker-compose; chmod 777 /usr/local/bin/docker-compose; systemctl enable docker
CMD ["/usr/sbin/init"]
